-- modernz :: modules/config.lua (generated by modularization refactor)

local msg = require "mp.msg"

local core = require("modules.core")
local state = core.state
local user_opts = require("modules.options")

local _locale = require("modules.locale")
local language = _locale.language

local function validate_user_opts()
    if not language[user_opts.language] then
       msg.warn("language '" .. user_opts.language .. "' not found. Ignoring.")
       user_opts.language = "default"
       if not language["default"] then
          msg.warn("ERROR: can't find the default language or the one set by user_opts.")
       end
    end

    if user_opts.seek_handle_size < 0 then
        msg.warn("seek_handle_size must be 0 or higher. Setting it to 0 (minimum).")
        user_opts.seek_handle_size = 0
    elseif user_opts.seek_handle_size > 1 then
        msg.warn("seek_handle_size must be 1 or lower. Setting it to 1 (maximum).")
        user_opts.seek_handle_size = 1
    end

    local function validate_string_opt(key, valid, default)
        for _, v in ipairs(valid) do
            if user_opts[key] == v then return end
        end
        msg.warn(key .. " value '" .. tostring(user_opts[key]) .. "' is invalid. Resetting to '" .. default .. "'.")
        user_opts[key] = default
    end
    validate_string_opt("window_top_bar", {"auto", "yes", "no"}, "auto")
    validate_string_opt("volume_control_type", {"linear", "logarithmic"}, "linear")
    validate_string_opt("keeponpause",  {"no", "bottombar", "both"}, "no")
    validate_string_opt("deadzone_hide", {"instant", "timeout"}, "instant")
    -- enum options that used to fall back silently on invalid values now warn and reset
    validate_string_opt("icon_theme",    {"fluent", "material"}, "fluent")
    validate_string_opt("icon_style",    {"mixed", "filled", "outline"}, "mixed")
    validate_string_opt("layout",        {"default", "compact", "mini", "seekbar"}, "default")
    validate_string_opt("time_format",   {"dynamic", "fixed"}, "dynamic")
    validate_string_opt("nibbles_style", {"gap", "triangle", "bar", "single-bar"}, "gap")
    validate_string_opt("jump_mode",     {"relative", "exact"}, "relative")

    local hbc = user_opts.seek_handle_border_color
    if hbc == "disable" then
        hbc = ""
    elseif hbc ~= "" and hbc:find("^#%x%x%x%x%x%x$") == nil then
        msg.warn("'" .. hbc .. "' is not a valid color for seek_handle_border_color, border disabled")
        hbc = ""
    end
    user_opts.seek_handle_border_color = hbc

    -- color options are reset to their defaults on invalid values so a typo
    -- can't leave garbage color tags in the generated ASS. The exception is
    -- seek_handle_border_color, which intentionally allows "disable"/"" and is
    -- normalized above.
    local color_defaults = {
        osc_color = "#000000",
        window_title_color = "#FFFFFF",
        window_controls_color = "#FFFFFF",
        windowcontrols_close_hover = "#F45C5B",
        windowcontrols_max_hover = "#F8BC3A",
        windowcontrols_min_hover = "#43CB44",
        title_color = "#FFFFFF",
        cache_info_color = "#FFFFFF",
        seekbar_cache_color = "#B1B1B1",
        seekbarfg_color = "#FF8232",
        seekbarbg_color = "#999999",
        seek_handle_color = "#C96508",
        time_color = "#FFFFFF",
        chapter_title_color = "#FFFFFF",
        side_buttons_color = "#FFFFFF",
        middle_buttons_color = "#FFFFFF",
        playpause_color = "#FFFFFF",
        held_element_color = "#999999",
        hover_effect_color = "#FF8232",
        thumbnail_box_color = "#111111",
        thumbnail_box_outline = "#404040",
        nibble_color = "#FF8232",
        nibble_current_color = "#FFFFFF",
        ab_loop_color = "#2596be",
    }

    for key, default in pairs(color_defaults) do
        local color = user_opts[key]
        if type(color) ~= "string" or color:find("^#%x%x%x%x%x%x$") == nil then
            msg.warn("'" .. tostring(color) .. "' is not a valid color for " .. key .. ". Resetting to '" .. default .. "'.")
            user_opts[key] = default
        end
    end

    -- surface unknown hover_effect tokens instead of silently ignoring them
    for token in string.gmatch(user_opts.hover_effect, "([^,]+)") do
        local t = token:match("^%s*(.-)%s*$")
        if t ~= "size" and t ~= "color" and t ~= "glow" and t ~= "box" then
            msg.warn("Ignoring unknown hover_effect '" .. t .. "'")
        end
    end

    state.visibility_modes = {}
    for str in string.gmatch(user_opts.visibility_modes, "([^_]+)") do
        if str ~= "auto" and str ~= "always" and str ~= "never" then
            msg.warn("Ignoring unknown visibility mode '" .. str .."' in list")
        else
            table.insert(state.visibility_modes, str)
        end
    end

    if user_opts.keeponpause ~= "no" and not user_opts.showonpause then
        msg.warn("keeponpause requires showonpause. Setting showonpause=yes.")
        user_opts.showonpause = true
    end

    local watch_later = "," .. ((mp.get_property("options/watch-later-options") or ""):gsub("%s+", "")) .. ","
    if user_opts.sub_margins and watch_later:find(",sub-pos,", 1, true) then
        msg.warn("sub_margins conflict: add watch-later-options-remove=sub-pos to mpv.conf")
    end
    if user_opts.osd_margins and watch_later:find(",osd-margin-y,", 1, true) then
        msg.warn("osd_margins conflict: add watch-later-options-remove=osd-margin-y to mpv.conf")
    end
end

return {
    validate_user_opts = validate_user_opts,
}
