-- modernz :: modules/control.lua (generated by modularization refactor)

local msg = require "mp.msg"

local core = require("modules.core")
local state = core.state
local user_opts = require("modules.options")

local tick_delay = 1 / 60
-- tick() is defined in the events module; injected here at load time via
-- set_tick(). Every entry point that needs it goes through ensure_tick(),
-- which fails loudly instead of leaving a nil passed into mp.add_timeout.
local tick
local function set_tick(fn) tick = fn end

local function ensure_tick()
    if not tick then
        msg.error("control.lua: tick() requested before set_tick() was called - ignoring. " ..
                   "This means module load order is wrong (events.lua must call set_tick() at load time).")
        return false
    end
    return true
end

local function request_tick()
    if not ensure_tick() then return end

    if state.tick_timer == nil then
        state.tick_timer = mp.add_timeout(0, tick)
    end

    if not state.tick_timer:is_enabled() then
        local now = mp.get_time()
        local timeout = tick_delay - (now - state.tick_last_time)
        if timeout < 0 then
            timeout = 0
        end
        state.tick_timer.timeout = timeout
        state.tick_timer:resume()
    end
end

local function request_init()
    state.initREQ = true
    request_tick()
end

local function request_init_resize()
    request_init()
    if not state.tick_timer then return end
    -- ensure immediate update
    state.tick_timer:kill()
    state.tick_timer.timeout = 0
    state.tick_timer:resume()
end

local function set_tick_delay(_, display_fps)
    -- may be nil if unavailable, or 0 if a display reports 0 fps; guard both
    -- so a stale 0 can't produce tick_delay = 1/0 = inf
    if not display_fps or display_fps <= 0 or not user_opts.tick_delay_follow_display_fps then
        tick_delay = user_opts.tick_delay
        return
    end
    tick_delay = 1 / display_fps
end

return {
    request_tick = request_tick,
    request_init = request_init,
    request_init_resize = request_init_resize,
    set_tick_delay = set_tick_delay,
    set_tick = set_tick,
}
