-- modernz :: modules/media.lua (generated by modularization refactor)

local msg = require "mp.msg"
local utils = require "mp.utils"

local core = require("modules.core")
local state = core.state
local user_opts = require("modules.options")

local _control = require("modules.control")
local request_tick = _control.request_tick

local function is_image()
    local t = mp.get_property_native("current-tracks/video")
    state.is_image = t ~= nil and t.image == true and t.albumart ~= true
end

local function get_ytdl_format()
    local fmt = mp.get_property("file-local-options/ytdl-format") or mp.get_property("ytdl-format") or ""
    return fmt ~= "" and ("-f " .. fmt) or "-f bestvideo+bestaudio/best"
end

local function exec(args, callback, timeout)
    for i = #args, 1, -1 do
        if args[i] == nil or args[i] == "" then table.remove(args, i) end
    end
    msg.info("Executing: " .. table.concat(args, " "))
    local cmd = {
        name = "subprocess",
        args = args,
        capture_stdout = true,
        capture_stderr = true,
    }
    -- optional timeout in ms (0/nil = no timeout); prevents silent background
    -- probes (e.g. yt-dlp size approximation) from hanging forever. Unsupported
    -- on mpv < 0.36, where the field is simply ignored.
    if timeout then cmd.timeout = timeout end
    mp.command_native_async(cmd, callback)
end

local function check_path_url()
    state.is_url = false
    state.downloading = false

    local path = mp.get_property("path")
    if not path then return end

    -- normalize ytdl:// prefix: ytdl://https://... > https://..., ytdl://... > https://...
    path = path:gsub("^ytdl://https?://", "https://"):gsub("^ytdl://", "https://")

    local scheme = path:match("^([%w][%w+%-%.]*)://")
    local online_schemes = {
        http=true, https=true,
        ftp=true, ftps=true,
        rtmp=true, rtmps=true,
        rtsp=true, rtsps=true,
        mms=true, mmsh=true, mmst=true,
    }

    if scheme and online_schemes[scheme:lower()] then
        state.is_url = true
        state.url_path = path
        msg.info("URL detected.")

        if user_opts.download_button then
            msg.info("Approximating file size...")
            state.file_size_normalized = "Approximating file size..."
            exec({
                "yt-dlp",
                state.is_image and "" or get_ytdl_format(),
                "--no-download",
                "-O", "%(filesize,filesize_approx)s",
                path
            }, function(_, result)
                local bytes = tonumber(result.stdout)
                if bytes then
                    state.file_size_normalized = utils.format_bytes_humanized(bytes)
                    msg.info("Download size: " .. state.file_size_normalized)
                else
                    local fs_prop = mp.get_property_osd("file-size")
                    if fs_prop and fs_prop ~= "" then
                        state.file_size_normalized = fs_prop
                        msg.info("Download size: " .. fs_prop)
                    else
                        state.file_size_normalized = "Unknown"
                        msg.info("Unable to retrieve file size.")
                    end
                end
                request_tick()
            end, 30000)
        end
    end
end

local function download_done(success, _, error)
    if success then
        local path = mp.command_native({"expand-path", user_opts.download_path})
        mp.commandv("show-text", "Download saved to " .. path, "-1", "1")
        state.downloaded_once = true
        msg.info("Download completed")
    else
        mp.commandv("show-text", "Download failed - " .. (error or "Unknown error"), "-1", "1")
        msg.info("Download failed")
    end
    state.downloading = false
end

return {
    is_image = is_image,
    get_ytdl_format = get_ytdl_format,
    exec = exec,
    check_path_url = check_path_url,
    download_done = download_done,
}
