-- modernz :: modules/media.lua (generated by modularization refactor)

local assdraw = require "mp.assdraw"
local msg = require "mp.msg"
local opt = require "mp.options"
local utils = require "mp.utils"

local shared = require("modules.state")
local state = shared.state
local osc_param = shared.osc_param
local thumbfast = shared.thumbfast
local icons = shared.icons
local osc_styles = shared.osc_styles
local locale = shared.locale
local seekbar_height_style = shared.seekbar_height_style
local elements = shared.elements
local layouts = shared.layouts
local hover_effects = shared.hover_effects
local text_width_cache = shared.text_width_cache
local user_opts = require("modules.options")

local _utils = require("modules.utils")
local contains = _utils.contains
local kill_animation = _utils.kill_animation
local set_osd = _utils.set_osd
local observe_cached = _utils.observe_cached
local get_virt_scale_factor = _utils.get_virt_scale_factor
local recently_touched = _utils.recently_touched
local get_virt_mouse_pos = _utils.get_virt_mouse_pos
local set_virt_mouse_area = _utils.set_virt_mouse_area
local scale_value = _utils.scale_value
local get_align = _utils.get_align
local estimate_text_width = _utils.estimate_text_width
local get_time_codes_width = _utils.get_time_codes_width
local get_hitbox_coords = _utils.get_hitbox_coords
local get_element_hitbox = _utils.get_element_hitbox
local mouse_hit_coords = _utils.mouse_hit_coords
local mouse_hit = _utils.mouse_hit
local mouse_in_area = _utils.mouse_in_area
local limit_range = _utils.limit_range
local get_slider_ele_pos_for = _utils.get_slider_ele_pos_for
local get_slider_value_at = _utils.get_slider_value_at
local get_slider_value = _utils.get_slider_value
local mult_alpha = _utils.mult_alpha
local add_area = _utils.add_area
local ass_append_alpha = _utils.ass_append_alpha
local draw_tooltip = _utils.draw_tooltip
local ass_draw_cir_cw = _utils.ass_draw_cir_cw
local ass_draw_rr_h_cw = _utils.ass_draw_rr_h_cw
local get_hidetimeout = _utils.get_hidetimeout
local get_touchtimeout = _utils.get_touchtimeout
local cache_enabled = _utils.cache_enabled
local set_margin_offset = _utils.set_margin_offset
local reset_margins = _utils.reset_margins
local update_margins = _utils.update_margins
local render_wipe = _utils.render_wipe
local set_volume = _utils.set_volume
local window_controls_enabled = _utils.window_controls_enabled
local format_time = _utils.format_time
local build_cache_seek_ranges = _utils.build_cache_seek_ranges
local _control = require("modules.control")
local request_tick = _control.request_tick
local request_init = _control.request_init
local request_init_resize = _control.request_init_resize
local set_tick_delay = _control.set_tick_delay
local set_tick = _control.set_tick

local function is_image()
    local t = mp.get_property_native("current-tracks/video")
    state.is_image = t ~= nil and t.image == true and t.albumart ~= true
end

local function get_ytdl_format()
    local fmt = mp.get_property("file-local-options/ytdl-format") or mp.get_property("ytdl-format") or ""
    return fmt ~= "" and ("-f " .. fmt) or "-f bestvideo+bestaudio/best"
end

local function exec(args, callback)
    for i = #args, 1, -1 do
        if args[i] == nil or args[i] == "" then table.remove(args, i) end
    end
    msg.info("Executing: " .. table.concat(args, " "))
    mp.command_native_async({
        name = "subprocess",
        args = args,
        capture_stdout = true,
        capture_stderr = true
    }, callback)
end

local function check_path_url()
    state.is_url = false
    state.downloading = false

    local path = mp.get_property("path")
    if not path then return end

    -- normalize ytdl:// prefix: ytdl://https://... > https://..., ytdl://... > https://...
    path = path:gsub("^ytdl://https?://", "https://"):gsub("^ytdl://", "https://")

    local scheme = path:match("^([%w][%w+%-%.]*)://")
    local online_schemes = {
        http=true, https=true,
        ftp=true, ftps=true,
        rtmp=true, rtmps=true,
        rtsp=true, rtsps=true,
        mms=true, mmsh=true, mmst=true,
    }

    if scheme and online_schemes[scheme:lower()] then
        state.is_url = true
        state.url_path = path
        msg.info("URL detected.")

        if user_opts.download_button then
            msg.info("Approximating file size...")
            state.file_size_normalized = "Approximating file size..."
            exec({
                "yt-dlp",
                state.is_image and "" or get_ytdl_format(),
                "--no-download",
                "-O", "%(filesize,filesize_approx)s",
                path
            }, function(_, result)
                local bytes = tonumber(result.stdout)
                if bytes then
                    state.file_size_normalized = utils.format_bytes_humanized(bytes)
                    msg.info("Download size: " .. state.file_size_normalized)
                else
                    local fs_prop = mp.get_property_osd("file-size")
                    if fs_prop and fs_prop ~= "" then
                        state.file_size_normalized = fs_prop
                        msg.info("Download size: " .. fs_prop)
                    else
                        state.file_size_normalized = "Unknown"
                        msg.info("Unable to retrieve file size.")
                    end
                end
                request_tick()
            end)
        end
    end
end

local function download_done(success, _, error)
    if success then
        local path = mp.command_native({"expand-path", user_opts.download_path})
        mp.commandv("show-text", "Download saved to " .. path, "-1", "1")
        state.downloaded_once = true
        msg.info("Download completed")
    else
        mp.commandv("show-text", "Download failed - " .. (error or "Unknown error"), "-1", "1")
        msg.info("Download failed")
    end
    state.downloading = false
end

return {
    is_image = is_image,
    get_ytdl_format = get_ytdl_format,
    exec = exec,
    check_path_url = check_path_url,
    download_done = download_done,
}
