-- modernz :: modules/styles.lua (generated by modularization refactor)

local assdraw = require "mp.assdraw"
local msg = require "mp.msg"
local opt = require "mp.options"
local utils = require "mp.utils"

local shared = require("modules.state")
local state = shared.state
local osc_param = shared.osc_param
local thumbfast = shared.thumbfast
local icons = shared.icons
local osc_styles = shared.osc_styles
local locale = shared.locale
local seekbar_height_style = shared.seekbar_height_style
local elements = shared.elements
local layouts = shared.layouts
local hover_effects = shared.hover_effects
local text_width_cache = shared.text_width_cache
local user_opts = require("modules.options")

local _utils = require("modules.utils")
local contains = _utils.contains
local kill_animation = _utils.kill_animation
local set_osd = _utils.set_osd
local observe_cached = _utils.observe_cached
local get_virt_scale_factor = _utils.get_virt_scale_factor
local recently_touched = _utils.recently_touched
local get_virt_mouse_pos = _utils.get_virt_mouse_pos
local set_virt_mouse_area = _utils.set_virt_mouse_area
local scale_value = _utils.scale_value
local get_align = _utils.get_align
local estimate_text_width = _utils.estimate_text_width
local get_time_codes_width = _utils.get_time_codes_width
local get_hitbox_coords = _utils.get_hitbox_coords
local get_element_hitbox = _utils.get_element_hitbox
local mouse_hit_coords = _utils.mouse_hit_coords
local mouse_hit = _utils.mouse_hit
local mouse_in_area = _utils.mouse_in_area
local limit_range = _utils.limit_range
local get_slider_ele_pos_for = _utils.get_slider_ele_pos_for
local get_slider_value_at = _utils.get_slider_value_at
local get_slider_value = _utils.get_slider_value
local mult_alpha = _utils.mult_alpha
local add_area = _utils.add_area
local ass_append_alpha = _utils.ass_append_alpha
local draw_tooltip = _utils.draw_tooltip
local ass_draw_cir_cw = _utils.ass_draw_cir_cw
local ass_draw_rr_h_cw = _utils.ass_draw_rr_h_cw
local get_hidetimeout = _utils.get_hidetimeout
local get_touchtimeout = _utils.get_touchtimeout
local cache_enabled = _utils.cache_enabled
local set_margin_offset = _utils.set_margin_offset
local reset_margins = _utils.reset_margins
local update_margins = _utils.update_margins
local render_wipe = _utils.render_wipe
local set_volume = _utils.set_volume
local window_controls_enabled = _utils.window_controls_enabled
local format_time = _utils.format_time
local build_cache_seek_ranges = _utils.build_cache_seek_ranges

local function osc_color_convert(color)
    return color:sub(6,7) .. color:sub(4,5) ..  color:sub(2,3)
end

local function set_osc_styles()
    local playpause_size = user_opts.playpause_size
    local midbuttons_size = user_opts.midbuttons_size
    local sidebuttons_size = user_opts.sidebuttons_size

    hover_effects.size  = contains(user_opts.hover_effect, "size")
    hover_effects.color = contains(user_opts.hover_effect, "color")
    hover_effects.glow  = contains(user_opts.hover_effect, "glow")
    hover_effects.box   = contains(user_opts.hover_effect, "box")

    local seekbar_presets = {
        small  = { radius = 1, height = 2 },
        medium = { radius = 2, height = 4 },
        large  = { radius = 3, height = 6 },
        xlarge = { radius = 4, height = 8 }
    }
    local _sh = seekbar_presets[user_opts.seekbar_height] or seekbar_presets.medium
    for k in pairs(seekbar_height_style) do seekbar_height_style[k] = nil end
    for k, v in pairs(_sh) do seekbar_height_style[k] = v end

    local _os = {
        osc_fade_bg = "{\\blur" .. user_opts.fade_blur_strength .. "\\bord" .. user_opts.osc_fade_strength .. "\\1c&H0&\\3c&H" .. osc_color_convert(user_opts.osc_color) .. "&}",
        window_fade_bg = "{\\blur" .. user_opts.window_fade_blur_strength .. "\\bord" .. user_opts.window_fade_strength .. "\\1c&H0&\\3c&H" .. osc_color_convert(user_opts.osc_color) .. "&}",
        window_control = "{\\1c&H" .. osc_color_convert(user_opts.window_controls_color) .. "&\\fs25\\fn" .. icons.iconfont .. "}",
        window_title = "{\\bord1\\1c&H" .. osc_color_convert(user_opts.window_title_color) .. "&\\3c&H0&\\fs".. user_opts.window_title_font_size .."\\q2\\fn" .. user_opts.font .. "}",
        title = "{\\bord1\\1c&H" .. osc_color_convert(user_opts.title_color) .. "&\\3c&H0&\\fs".. user_opts.title_font_size .."\\q2\\fn" .. user_opts.font .. "}",
        chapter_title = "{\\bord1\\1c&H" .. osc_color_convert(user_opts.chapter_title_color) .. "&\\3c&H0&\\fs" .. user_opts.chapter_title_font_size .. "\\q2\\fn" .. user_opts.font .. "}",
        seekbar_bg = "{\\1c&H" .. osc_color_convert(user_opts.seekbarbg_color) .. "&}",
        seekbar_fg = "{\\blur1\\bord1\\1c&H" .. osc_color_convert(user_opts.seekbarfg_color) .. "&}",
        thumbnail = "{\\bord" .. user_opts.thumbnail_box_outline_size .. "\\1c&H" .. osc_color_convert(user_opts.thumbnail_box_color) .. "&\\3c&H" .. osc_color_convert(user_opts.thumbnail_box_outline) .. "&}",
        time = "{\\bord1\\1c&H" .. osc_color_convert(user_opts.time_color) .. "&\\3c&H0&\\fs" .. user_opts.time_font_size .. "\\fn" .. user_opts.font .. "}",
        cache = "{\\bord1\\1c&H" .. osc_color_convert(user_opts.cache_info_color) .. "&\\3c&H0&\\fs" .. user_opts.cache_info_font_size .. "\\fn" .. user_opts.font .. "}",
        tooltip = "{\\bord1\\1c&HFFFFFF&\\3c&H0&\\fs" .. user_opts.tooltip_font_size .. "\\fn" .. user_opts.font .. "}",
        tooltip_box = "{\\1c&H" .. osc_color_convert(user_opts.osc_color) .. "&}",
        speed = "{\\bord1\\1c&H" .. osc_color_convert(user_opts.side_buttons_color) .. "&\\3c&H0&\\fs" .. user_opts.speed_font_size .. "\\fn" .. user_opts.font .. "}",
        volumebar_bg = "{\\1c&H999999&}",
        volumebar_fg = "{\\blur1\\bord1\\1c&H" .. osc_color_convert(user_opts.side_buttons_color) .. "&}",
        control_1 = "{\\1c&H" .. osc_color_convert(user_opts.playpause_color) .. "&\\fs" .. playpause_size .. "\\fn" .. icons.iconfont .. "}",
        control_2 = "{\\1c&H" .. osc_color_convert(user_opts.middle_buttons_color) .. "&\\fs" .. midbuttons_size .. "\\fn" .. icons.iconfont .. "}",
        control_3 = "{\\1c&H" .. osc_color_convert(user_opts.side_buttons_color) .. "&\\fs" .. sidebuttons_size .. "\\fn" .. icons.iconfont .. "}",
        control_mini = "{\\1c&H" .. osc_color_convert(user_opts.side_buttons_color) .. "&\\fs16\\fn" .. icons.iconfont .. "}",
        element_down = "{\\1c&H" .. osc_color_convert(user_opts.held_element_color) .. "&" .. string.format("\\fscx%s\\fscy%s", user_opts.button_held_size, user_opts.button_held_size) .. "}",
        element_hover = "{" .. (hover_effects.color and "\\1c&H" .. osc_color_convert(user_opts.hover_effect_color) .. "&" or "") .. (hover_effects.size and string.format("\\fscx%s\\fscy%s", user_opts.button_hover_size, user_opts.button_hover_size) or "") .. "}",
        hover_bg = "{\\1c&H" .. osc_color_convert(user_opts.hover_effect_color) .. "&}",
    }
    for k in pairs(osc_styles) do osc_styles[k] = nil end
    for k, v in pairs(_os) do osc_styles[k] = v end
end

local function set_time_styles(timecurrent_changed, timems_changed)
    if timecurrent_changed then
        state.tc_left_rem = not user_opts.timecurrent
    end
    if timems_changed then
        state.tc_ms = user_opts.timems
    end
end

return {
    osc_color_convert = osc_color_convert,
    set_osc_styles = set_osc_styles,
    set_time_styles = set_time_styles,
}
